### ISSUE TITLE
Type Error when running with Python 3.8

### ISSUE THREAD

**Issue by hamilton-function** [samoturk/mol2vec#15]
When running with Python 3.8, I get the following error message:

Featurizing molecules.
Traceback (most recent call last):
  File "/Users/dkazempour/opt/anaconda3/bin/mol2vec", line 8, in <module>
    sys.exit(run())
  File "/Users/dkazempour/opt/anaconda3/lib/python3.8/site-packages/mol2vec/app/mol2vec.py", line 165, in run
    args.func(args)
  File "/Users/dkazempour/opt/anaconda3/lib/python3.8/site-packages/mol2vec/app/mol2vec.py", line 25, in do_featurize
    features.featurize(args.in_file, args.out_file, args.model, args.radius, args.uncommon)
  File "/Users/dkazempour/opt/anaconda3/lib/python3.8/site-packages/mol2vec/features.py", line 465, in featurize
    word2vec_model[uncommon]
TypeError: 'Word2Vec' object is not subscriptable

Which library is causing this issue? 

Update: I recognized that my observation is related to the other issue titled "update sentences2vec function for gensim 4.0" by Maledive. 

The causing library is gensim. Something has changed at the 4.x.x versions, which yields the above stated error. 

A temporary 'fix' (actually a quite quick-n-dirty hack) is as follows: pip install -Iv gensim==3.8.2
Afterwards I could successfully run mol2vec again.

**Comment by m-liddell** [comment]
It seems as of Gensim 4.0 & higher, the Word2Vec model doesn't support subscripted-indexed access https://stackoverflow.com/questions/67687962/typeerror-word2vec-object-is-not-subscriptable
